#!/bin/bash
#Script to back up various configuration (and a plugin) files to a tarball
mv /home/james/Dropbox/backups/configs.tar.gz /home/james/Dropbox/backups/old_configs.tar.gz

#Record partition scheme
df -h > partitions

sudo tar -czp -f /home/james/Dropbox/backups/configs.tar.gz \
./partitions \
/etc/rc.d/rc.inet1 \
/etc/rc.d/rc.inet1.conf \
/etc/modprobe.d/snd-hda-intel.conf \
/etc/acpi/acpi_handler.sh \
/etc/wpa_supplicant.conf \
/etc/udev/rules.d/51-android.rules \
/etc/wpa_supplicant.conf.norfolk \
/etc/wpa_supplicant.conf.weston \
/etc/slackpkg/mirrors \
/home/james/.bash_aliases \
/home/james/.bash_profile \
/home/james/.bashrc \
/home/james/.vimrc \
/home/james/.vim/ \
/home/james/.vim/plugin/ \
/home/james/.vim/doc/ \
/home/james/.xchat2/servlist_.conf \
/home/james/.xinitrc \
/home/james/.xprofile \
/home/james/.xsessionrc \
/home/james/.config/ \
/home/james/.mozilla/plugins/libflashplayer.so \
/usr/bin/xflock4

#Clean up
rm partitions

#Ensure dropboxd is started
su james -c "python /usr/local/bin/dropbox.py start"

